#! /usr/bin/bash

cd wr-only_o2
sh test_numa.sh
cd ../1w4r_o2
sh test_numa.sh
cd ../3sten_o2
sh test_numa.sh
cd ../5sten_o2
sh test_numa.sh
cd ../7sten_o2
sh test_numa.sh
cd ../9sten_o2
sh test_numa.sh
cd ../27sten_o2
sh test_numa.sh
cd ../wr-only_nvm_o2
sh test_numa.sh
cd ../1w4r_nvm_o2
sh test_numa.sh
cd ../3sten_nvm_o2
sh test_numa.sh
cd ../5sten_nvm_o2
sh test_numa.sh
cd ../7sten_nvm_o2
sh test_numa.sh
cd ../9sten_nvm_o2
sh test_numa.sh
cd ../27sten_nvm_o2
sh test_numa.sh
cd ../O2_optimized
sh test_numa.sh
