#! /usr/bin/bash

cd wr-only
sh test_numa.sh
cd ../1w4r
sh test_numa.sh
cd ../3sten
sh test_numa.sh
cd ../5sten
sh test_numa.sh
cd ../7sten
sh test_numa.sh
cd ../9sten
sh test_numa.sh
cd ../27sten
sh test_numa.sh
cd ../wr-only_nvm
sh test_numa.sh
cd ../1w4r_nvm
sh test_numa.sh
cd ../3sten_nvm
sh test_numa.sh
cd ../5sten_nvm
sh test_numa.sh
cd ../7sten_nvm
sh test_numa.sh
cd ../9sten_nvm
sh test_numa.sh
cd ../27sten_nvm
sh test_numa.sh
